# Generated by Django 5.1.7 on 2025-03-18 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistenciaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscrito_cad_unico', models.BooleanField(default=False)),
                ('beneficiario_bolsa_familia', models.BooleanField(default=False)),
                ('recebe_auxilio_moradia', models.BooleanField(default=False)),
                ('recebe_bpc', models.BooleanField(default=False)),
                ('renda_familiar', models.CharField(choices=[('ATE_MEIO', 'Até 1/2 SM'), ('UM_A_DOIS', '1 A 2 SM'), ('TRES_A_QUATRO', '03 A 04 SM'), ('ACIMA_QUATRO', 'Acima de 04 SM')], max_length=45)),
                ('renda_per_capita', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui_radio', models.BooleanField(default=False)),
                ('possui_bicicleta', models.BooleanField(default=False)),
                ('possui_tv', models.BooleanField(default=False)),
                ('possui_computador', models.BooleanField(default=False)),
                ('possui_celular', models.BooleanField(default=False)),
                ('possui_fogao', models.BooleanField(default=False)),
                ('possui_geladeira', models.BooleanField(default=False)),
                ('possui_microondas', models.BooleanField(default=False)),
                ('equipamentos_estado', models.CharField(choices=[('NOVOS', 'Novos'), ('USADOS', 'Usados')], max_length=45)),
                ('equipamentos_recursos_proprios', models.BooleanField(default=False)),
                ('equipamentos_presenteados', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('bairro', models.CharField(max_length=100)),
                ('microrregiao', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('EDUCACAO_INFANTIL', 'Educação Infantil'), ('FUNDAMENTAL_INCOMPLETO', 'Fundamental Incompleto'), ('FUNDAMENTAL_COMPLETO', 'Fundamental Completo'), ('MEDIO_INCOMPLETO', 'Médio Incompleto'), ('MEDIO_COMPLETO', 'Médio Completo'), ('CURSO_TECNICO', 'Curso Técnico'), ('SUPERIOR_INCOMPLETO', 'Superior Incompleto'), ('SUPERIOR_COMPLETO', 'Superior Completo'), ('POS_GRADUACAO', 'Pós Graduação'), ('NAO_ACESSA_REDE_FORMAL', 'Não Acessa a Rede Formal de Ensino')], max_length=45)),
                ('tipo_rede', models.CharField(choices=[('REDE_PUBLICA', 'Rede Pública'), ('REDE_PRIVADA', 'Rede Privada')], max_length=45)),
                ('ano_ou_periodo', models.CharField(blank=True, max_length=45, null=True)),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('INTEGRAL', 'Integral')], max_length=45)),
                ('motivo_nao_estuda', models.TextField(blank=True, null=True)),
                ('deseja_estudar', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoComunitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COOPERATIVA', 'Cooperativa'), ('ASSOCIACAO', 'Associação'), ('GRUPO_RELIGIOSO', 'Grupo Religioso'), ('IGREJA', 'Igreja'), ('OUTRO', 'Outro')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='HabitoAlimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VERDURA', 'Verdura'), ('CARNE_VERMELHA', 'Carne Vermelha'), ('FRANGO', 'Frango'), ('PEIXE', 'Peixe'), ('LEITE', 'Leite'), ('FEIJAO', 'Feijão')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Moradia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_casa', models.CharField(choices=[('PROPRIA', 'Própria'), ('ALUGADA', 'Alugada'), ('OCUPACAO', 'Ocupação'), ('CEDIDA', 'Cedida'), ('OUTRO', 'Outro')], max_length=45)),
                ('material_casa', models.CharField(choices=[('ALVENARIA', 'Alvenaria-Tijolos'), ('MADEIRA', 'Madeira'), ('TAIPA_REVESTIDA', 'Taipa Revestida'), ('TAIPA_NAO_REVESTIDA', 'Taipa Não Revestida'), ('MATERIAL_APROVEITADO', 'Material Aproveitado'), ('OUTRO', 'Outro')], max_length=45)),
                ('risco_alagamento', models.BooleanField(default=False)),
                ('risco_deslizamento', models.BooleanField(default=False)),
                ('numero_comodos', models.IntegerField()),
                ('tem_divisoria_criancas_adultos', models.BooleanField(default=False)),
                ('tem_banheiro', models.BooleanField(default=False)),
                ('banheiro_dentro_casa', models.BooleanField(default=False)),
                ('energia_eletrica', models.BooleanField(default=False)),
                ('condicoes_agua', models.CharField(choices=[('REDE_PUBLICA', 'Rede Pública'), ('POCO', 'Poço'), ('RIO_ACUDE', 'Rio/Açude'), ('SEM_AGUA', 'Não tem disponibilidade de água'), ('OUTROS', 'Outros')], max_length=45)),
                ('destino_lixo', models.CharField(choices=[('COLETADO', 'Coletado'), ('QUEIMADO', 'Queimado/Enterrado'), ('CEU_ABERTO', 'Céu Aberto'), ('RIO', 'Rio'), ('OUTRO', 'Outro')], max_length=45)),
                ('destino_fezes', models.CharField(choices=[('REDE_GERAL', 'Sistema de Esgoto - Rede Geral'), ('FOSSA', 'Fossa'), ('CEU_ABERTO', 'Céu Aberto'), ('RIO', 'Rio'), ('OUTRO', 'Outro')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='NocoesComplementares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conhece_eca', models.CharField(choices=[('CONHECO', 'Conheço'), ('OUVI_FALAR', 'Já ouvi falar'), ('NAO_CONHECO', 'Não Conheço')], max_length=45)),
                ('nocao_direitos_deveres', models.BooleanField(default=False)),
                ('referencia_familiar', models.CharField(choices=[('POSITIVA', 'Positiva'), ('NEGATIVA', 'Negativa')], max_length=45)),
                ('conhece_conselho_direito', models.CharField(choices=[('CONHECO', 'Conheço'), ('OUVI_FALAR', 'Já ouvi falar'), ('NAO_CONHECO', 'Não Conheço')], max_length=45)),
                ('qual_conselho', models.CharField(blank=True, choices=[('CRIANCA', 'Criança'), ('ASSISTENCIA', 'Assistência'), ('IDOSO', 'Idoso'), ('SAUDE', 'Saúde'), ('EDUCACAO', 'Educação')], max_length=45, null=True)),
                ('conhece_foscar', models.CharField(choices=[('CONHECO', 'Conheço'), ('OUVI_FALAR', 'Já ouvi falar'), ('NAO_CONHECO', 'Não Conheço')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True)),
                ('raca_cor', models.CharField(blank=True, choices=[('BRANCA', 'Branca'), ('PRETA', 'Preta'), ('PARDA', 'Parda'), ('AMARELA', 'Amarela'), ('INDIGENA', 'Indígena'), ('NAO_DECLARADO', 'Não Declarado')], max_length=45, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('whatsapp', models.BooleanField(default=False)),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO_ESTAVEL', 'União Estável'), ('OUTRO', 'Outro')], max_length=45, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SituacaoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('EMPREGO_FORMAL', 'Emprego Formal - CLT, Concurso, etc'), ('DESEMPREGADO', 'Desempregado(a)'), ('EMPREGO_INFORMAL', 'Emprego Informal/Biscates'), ('APOSENTADO', 'Aposentado(a)/Benefício'), ('MENOR_APRENDIZ', 'Menor Aprendiz'), ('JOVEM_APRENDIZ', 'Jovem Aprendiz'), ('APENAS_ESTUDA', 'Apenas Estuda'), ('DO_LAR', 'Do Lar'), ('OUTROS', 'Outros')], max_length=45)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('local_trabalho', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro_trabalho', models.CharField(blank=True, max_length=100, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SituacaoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_saude', models.BooleanField(default=False)),
                ('qual_plano_saude', models.CharField(blank=True, max_length=100, null=True)),
                ('teve_problema_saude', models.BooleanField(default=False)),
                ('teve_acompanhamento_medico', models.BooleanField(default=False)),
                ('ja_fez_cirurgia', models.BooleanField(default=False)),
                ('problema_saude_atual', models.TextField(blank=True, null=True)),
                ('deficiencia_fisica', models.BooleanField(default=False)),
                ('qual_deficiencia', models.CharField(blank=True, max_length=100, null=True)),
                ('condicao_desenvolvimento', models.CharField(blank=True, choices=[('TDAH', 'Déficit de Atenção e Hiperatividade (TDAH)'), ('AUTISMO', 'Autismo'), ('DEPRESSAO', 'Depressão'), ('TRANSTORNO_BIPOLAR', 'Transtorno Bipolar'), ('DISTURBIO_BIPOLAR', 'Distúrbio Bipolar Comportamental'), ('DIFICULDADE_APRENDIZAGEM', 'Dificuldade de Aprendizagem'), ('ATRASO_MENTAL', 'Atraso Mental')], max_length=45, null=True)),
                ('local_atendimento_saude', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=45)),
                ('sobrenomes', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('raca_cor', models.CharField(choices=[('BRANCA', 'Branca'), ('PRETA', 'Preta'), ('PARDA', 'Parda'), ('AMARELA', 'Amarela'), ('INDIGENA', 'Indígena'), ('NAO_DECLARADO', 'Não Declarado')], max_length=45)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('possui_whatsapp', models.BooleanField(default=False)),
                ('estado_civil', models.CharField(choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO_ESTAVEL', 'União Estável'), ('OUTRO', 'Outro')], max_length=45)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=45)),
                ('apadrinhado', models.BooleanField(default=False)),
                ('ingressara_projeto', models.CharField(max_length=100)),
                ('refeicoes_dia', models.IntegerField()),
                ('igreja_qual', models.CharField(blank=True, max_length=100, null=True)),
                ('outro_grupo', models.CharField(blank=True, max_length=100, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('assistencia_social', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.assistenciasocial')),
                ('bens', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.bens')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.endereco')),
                ('escolaridade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.escolaridade')),
                ('grupos_comunitarios', models.ManyToManyField(to='main.grupocomunitario')),
                ('habitos_alimentares', models.ManyToManyField(to='main.habitoalimentar')),
                ('moradia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.moradia')),
                ('nocoes_complementares', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.nocoescomplementares')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.responsavel')),
                ('situacao_profissional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.situacaoprofissional')),
                ('situacao_saude', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.situacaosaude')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['primeiro_nome', 'sobrenomes'],
            },
        ),
    ]
