# Generated by Django 5.1.6 on 2025-02-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_index=True, max_length=100)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_index=True, max_length=100)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('cursos', models.ManyToManyField(related_name='materias', to='main.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('primeiro_nome', models.CharField(max_length=50)),
                ('ultimo_nome', models.CharField(max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=225, unique=True)),
                ('senha_hashurada', models.TextField()),
                ('ano_comecou_ensinar', models.PositiveIntegerField()),
                ('salario', models.FloatField()),
                ('telefone', models.CharField(blank=True, max_length=25, null=True)),
                ('data_nascimento', models.DateField()),
                ('cursos', models.ManyToManyField(related_name='professores', to='main.curso')),
                ('materias', models.ManyToManyField(related_name='professores', to='main.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('primeiro_nome', models.CharField(max_length=50)),
                ('ultimo_nome', models.CharField(max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=225, unique=True)),
                ('senha_hashurada', models.TextField()),
                ('data_nascimento', models.DateField()),
                ('cursos', models.ManyToManyField(related_name='alunos', to='main.curso')),
                ('materias', models.ManyToManyField(related_name='alunos', to='main.materia')),
                ('professores', models.ManyToManyField(related_name='alunos', to='main.professor')),
            ],
        ),
    ]
