# Generated by Django 5.1.7 on 2025-03-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='assistencia_social',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='bens',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='escolaridade',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='grupos_comunitarios',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='habitos_alimentares',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='moradia',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nocoes_complementares',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='situacao_profissional',
            field=models.CharField(blank=True, choices=[('EMPREGO_FORMAL', 'Emprego Formal - CLT, Concurso, etc'), ('DESEMPREGADO', 'Desempregado(a)'), ('EMPREGO_INFORMAL', 'Emprego Informal/Biscates'), ('APOSENTADO', 'Aposentado(a)/Benefício'), ('MENOR_APRENDIZ', 'Menor Aprendiz'), ('JOVEM_APRENDIZ', 'Jovem Aprendiz'), ('APENAS_ESTUDA', 'Apenas Estuda'), ('DO_LAR', 'Do Lar'), ('OUTROS', 'Outros')], max_length=45, null=True),
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='situacao_saude',
        ),
        migrations.AddField(
            model_name='aluno',
            name='ano_ou_periodo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='bairro_trabalho',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='banheiro_dentro_casa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='beneficiario_bolsa_familia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='condicao_desenvolvimento',
            field=models.CharField(blank=True, choices=[('TDAH', 'Déficit de Atenção e Hiperatividade (TDAH)'), ('AUTISMO', 'Autismo'), ('DEPRESSAO', 'Depressão'), ('TRANSTORNO_BIPOLAR', 'Transtorno Bipolar'), ('DISTURBIO_BIPOLAR', 'Distúrbio Bipolar Comportamental'), ('DIFICULDADE_APRENDIZAGEM', 'Dificuldade de Aprendizagem'), ('ATRASO_MENTAL', 'Atraso Mental')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='condicoes_agua',
            field=models.CharField(blank=True, choices=[('REDE_PUBLICA', 'Rede Pública'), ('POCO', 'Poço'), ('RIO_ACUDE', 'Rio/Açude'), ('SEM_AGUA', 'Não tem disponibilidade de água'), ('OUTROS', 'Outros')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='conhece_conselho_direito',
            field=models.CharField(blank=True, choices=[('CONHECO', 'Conheço'), ('OUVI_FALAR', 'Já ouvi falar'), ('NAO_CONHECO', 'Não Conheço')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='conhece_eca',
            field=models.CharField(blank=True, choices=[('CONHECO', 'Conheço'), ('OUVI_FALAR', 'Já ouvi falar'), ('NAO_CONHECO', 'Não Conheço')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='conhece_foscar',
            field=models.CharField(blank=True, choices=[('CONHECO', 'Conheço'), ('OUVI_FALAR', 'Já ouvi falar'), ('NAO_CONHECO', 'Não Conheço')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='deficiencia_fisica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='deseja_estudar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='destino_fezes',
            field=models.CharField(blank=True, choices=[('REDE_GERAL', 'Sistema de Esgoto - Rede Geral'), ('FOSSA', 'Fossa'), ('CEU_ABERTO', 'Céu Aberto'), ('RIO', 'Rio'), ('OUTRO', 'Outro')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='destino_lixo',
            field=models.CharField(blank=True, choices=[('COLETADO', 'Coletado'), ('QUEIMADO', 'Queimado/Enterrado'), ('CEU_ABERTO', 'Céu Aberto'), ('RIO', 'Rio'), ('OUTRO', 'Outro')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='energia_eletrica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='equipamentos_estado',
            field=models.CharField(blank=True, choices=[('NOVOS', 'Novos'), ('USADOS', 'Usados')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='equipamentos_presenteados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='equipamentos_recursos_proprios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='inscrito_cad_unico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='ja_fez_cirurgia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='local_atendimento_saude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='local_trabalho',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='material_casa',
            field=models.CharField(blank=True, choices=[('ALVENARIA', 'Alvenaria-Tijolos'), ('MADEIRA', 'Madeira'), ('TAIPA_REVESTIDA', 'Taipa Revestida'), ('TAIPA_NAO_REVESTIDA', 'Taipa Não Revestida'), ('MATERIAL_APROVEITADO', 'Material Aproveitado'), ('OUTRO', 'Outro')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='microrregiao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='motivo_nao_estuda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nivel_escolaridade',
            field=models.CharField(blank=True, choices=[('EDUCACAO_INFANTIL', 'Educação Infantil'), ('FUNDAMENTAL_INCOMPLETO', 'Fundamental Incompleto'), ('FUNDAMENTAL_COMPLETO', 'Fundamental Completo'), ('MEDIO_INCOMPLETO', 'Médio Incompleto'), ('MEDIO_COMPLETO', 'Médio Completo'), ('CURSO_TECNICO', 'Curso Técnico'), ('SUPERIOR_INCOMPLETO', 'Superior Incompleto'), ('SUPERIOR_COMPLETO', 'Superior Completo'), ('POS_GRADUACAO', 'Pós Graduação'), ('NAO_ACESSA_REDE_FORMAL', 'Não Acessa a Rede Formal de Ensino')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nocao_direitos_deveres',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='numero_comodos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='plano_saude',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='possui_bicicleta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='possui_celular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='possui_computador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='possui_fogao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='possui_geladeira',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='possui_microondas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='possui_radio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='possui_tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='problema_saude_atual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='qual_conselho',
            field=models.CharField(blank=True, choices=[('CRIANCA', 'Criança'), ('ASSISTENCIA', 'Assistência'), ('IDOSO', 'Idoso'), ('SAUDE', 'Saúde'), ('EDUCACAO', 'Educação')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='qual_deficiencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='qual_plano_saude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='recebe_auxilio_moradia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='recebe_bpc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='referencia_familiar',
            field=models.CharField(blank=True, choices=[('POSITIVA', 'Positiva'), ('NEGATIVA', 'Negativa')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='renda_familiar',
            field=models.CharField(blank=True, choices=[('ATE_MEIO', 'Até 1/2 SM'), ('UM_A_DOIS', '1 A 2 SM'), ('TRES_A_QUATRO', '03 A 04 SM'), ('ACIMA_QUATRO', 'Acima de 04 SM')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='renda_per_capita',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='risco_alagamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='risco_deslizamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='tem_banheiro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='tem_divisoria_criancas_adultos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='teve_acompanhamento_medico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='teve_problema_saude',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='tipo_casa',
            field=models.CharField(blank=True, choices=[('PROPRIA', 'Própria'), ('ALUGADA', 'Alugada'), ('OCUPACAO', 'Ocupação'), ('CEDIDA', 'Cedida'), ('OUTRO', 'Outro')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='tipo_rede_escolar',
            field=models.CharField(blank=True, choices=[('REDE_PUBLICA', 'Rede Pública'), ('REDE_PRIVADA', 'Rede Privada')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turno_escolar',
            field=models.CharField(blank=True, choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('INTEGRAL', 'Integral')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='refeicoes_dia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AssistenciaSocial',
        ),
        migrations.DeleteModel(
            name='Bens',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Escolaridade',
        ),
        migrations.DeleteModel(
            name='GrupoComunitario',
        ),
        migrations.AddField(
            model_name='aluno',
            name='grupos_comunitarios',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='HabitoAlimentar',
        ),
        migrations.AddField(
            model_name='aluno',
            name='habitos_alimentares',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Moradia',
        ),
        migrations.DeleteModel(
            name='NocoesComplementares',
        ),
        migrations.DeleteModel(
            name='SituacaoProfissional',
        ),
        migrations.DeleteModel(
            name='SituacaoSaude',
        ),
    ]
